Better documentation for alpha1 constituent weighting
fmihpc/vlasiator pull request #1001
Opened 2024-06-19 13:47 UTC by lkotipal

2024-06-19 13:48 UTC, lkotipal commented
@ykempf Better? Not sure if these can be explained better without mathematical typesetting

2024-06-20 08:41 UTC, ykempf requested changes

2024-06-20 08:41 UTC, ykempf commented on parameters.cpp
> +   RP::add("AMR.alpha1_drho_weight","Multiplier for delta rho (particle density) in alpha calculation", 1.0);
particle -> plasma?

2024-06-20 08:41 UTC, ykempf commented on parameters.cpp
> +   RP::add("AMR.alpha1_du_weight","Multiplier for delta U (energy density) in alpha calculation", 1.0);
kinetic + field?

2024-10-10 09:06 UTC, markusbattarbee approved these changes

2024-10-10 09:23 UTC, merged