Remove vec from fluxfunction and fix compilation
fmihpc/vlasiator pull request #1029
Opened 2024-09-25 07:45 UTC by ykempf

This includes #1026 at the moment, apologies.

Adds fluxfunction to the tools built in github CI even though we don't use it (yet). That binary is not uploaded, either.

Fixes compilation of fluxfunction and removes the vectorclass from there, and the couple files it uses from particles/. Otherwise in particles/ only converting Vec3d to Vec3Dd so it compiles.

Neither fluxfunction nor particle pusher are tested so far!

2024-10-09 08:35 UTC, ursg requested changes
Well, hum. Functional thumbs up, because a working fluxfunction is obviously better than a broken one.

But instead of partially keeping with vectorclass and partially unrolling vector operations into handcrafted scalar operations, maybe the better way to go here would be to just switch to Eigen vectors, like in other parts of the code (like the ionosphere)?

Also, ```std::vector<double>``` as a vector type instead of ```std::array<double,3>``` really doesn't look right to me.

2024-10-09 08:35 UTC, ursg commented on particles/field.h
> +   std::vector<double> getCell(int x, int y, int z) {
I would suggest that this be ```std::array<double, 3>```. Because why would you use a variable-sized vector here?

2024-10-10 11:58 UTC, markusbattarbee commented
+1 for using Eigen vectors instead.

2024-10-18 18:41 UTC, ursg commented
[This](https://github.com/ykempf/vlasiator/pull/16) Pull request against this PR introduces Eigen vectors instead.

2025-02-04 17:12 UTC, ursg approved these changes

2025-02-05 10:43 UTC, ykempf commented on particles/boundaries.h
> +   Vec3Dd flip_v;
But so we still want to keep these as `vectorclass`, the others as `Eigen` vectors?

2025-02-05 10:43 UTC, ykempf commented on .github/workflows/github-ci.yml
> +        diff -q equatorial.bin /proj/group/spacephysics/vlasiator_testpackage/CI_reference/equatorial.bin
OK so this now reported nothing as expected, but if it were saying there's a diff it wouldn't be very prominent. How do we raise that?

2025-02-05 10:44 UTC, ykempf commented on particles/boundaries.h
> +   Vec3Dd flip_v;
Uh wait that's old.

2025-02-05 10:45 UTC, ykempf commented on particles/boundaries.h
> +   Vec3Dd flip_v;
But still a valid question from me.

2025-02-05 10:55 UTC, markusbattarbee commented on .github/workflows/github-ci.yml
> +        rm -rf run_20*
This will break in 75 years time! ;)

2025-02-05 10:55 UTC, markusbattarbee commented on .github/workflows/github-ci.yml
> +        diff -q equatorial.bin /proj/group/spacephysics/vlasiator_testpackage/CI_reference/equatorial.bin
pipe the output into a variable, and if the variable is acceptable, touch a file? then can have a yaml action checking for that file and failing on file not found?
@ursg might have a more elegant solution.

2025-02-05 10:55 UTC, markusbattarbee commented on particles/scenario.cpp
> +#define normalize_vector(v) (v).normalized()
These are already defined in relativistic_math.h

2025-02-05 10:55 UTC, markusbattarbee commented on particles/relativistic_math.h
> +
place in fields.h instead?

2025-02-05 10:55 UTC, markusbattarbee commented on particles/particle_post_pusher.cpp
> +
already defined in relativistic_math.h

2025-02-05 10:55 UTC, markusbattarbee commented on particles/histogram.h
> +         value = value.cwiseQuotient(high - low);
should this also be a macro like the other vector operations?

2025-02-05 12:07 UTC, ursg commented on particles/scenario.cpp
> +#define normalize_vector(v) (v).normalized()
I simply used these defines as a drop-in replacement for vectorclass. I originally took them from sysboundaries/ionosphere.cpp

So... maybe a global Eigen-as-vectorclass-header would make sense?

2025-03-19 12:43 UTC, merged