SysBoundary communicate VDFs only in smaller neighborhood
fmihpc/vlasiator pull request #1049
Opened 2024-11-01 10:13 UTC by ykempf

2024-11-04 11:33 UTC, ykempf commented
This is a subset of #1048 and will need more features/changes in any case.

2024-11-04 16:44 UTC, ykempf commented
So this is still not doing fluffy copy, which is used in copysphere, correctly. Will be fixed soon. I came back to this branch/PR as I am not taking in everything that was pushed to #1048. Mainly, I let it create (local) VDFs and compute their moments when needed, instead of adding spaghetti to save on that. What's expensive ar second-neighbour VDFs and their communication, not the actual local L2 VDFs.

2025-02-24 09:22 UTC, ykempf commented on datareduction/datareducer.cpp
> +            outputReducer->addOperator(new DRO::DataReductionOperatorPopulations<Real>(pop + "/vg_rho_r", i, offsetof(spatial_cell::Population, RHO_R), 1));
Ditch those again

2025-02-24 09:45 UTC, ykempf commented on sysboundary/ionosphere.cpp
> +      for (uint popID=0; popID<getObjectWrapper().particleSpecies.size(); ++popID) {
Are these needed?

2025-02-26 17:12 UTC, markusbattarbee commented on sysboundary/ionosphere.h
> +      virtual void setupL2OutflowAtRestart(
Instead of having these warnings in all the "wrong" boundaries, I think it should exist in the base class as a warning and be just missing from all the others.

2025-05-02 13:53 UTC, markusbattarbee requested changes
A Few minor suggestions still. But on a basic level this has been thoroughly tested in FIF so is fundamentallly sounds (though indeed total removal of L2 VDFs and their initialization as well would be a good idea at some point IMO)

2025-05-02 13:53 UTC, markusbattarbee commented on sysboundary/outflow.cpp
> +                              // at this stage we don't actually need the VDFs yet I think. And they were crashing LUMI apparently?!
Outdated comment, right?

2025-05-02 13:53 UTC, markusbattarbee commented on sysboundary/outflow.cpp
> +
Put the check for `if(mpiGrid[cellID]->sysBoundaryLayer == 1) {` here to skip earlier for cells we don't want to evaluate?

2025-05-02 13:53 UTC, markusbattarbee commented on sysboundary/outflow.cpp
> +
Put the check for `if(mpiGrid[cellID]->sysBoundaryLayer == 2) {` here to skip earlier for cells we don't want to evaluate?

2025-05-02 13:53 UTC, markusbattarbee commented on sysboundary/sysboundarycondition.cpp
> +            to->get_population(popID).V[i] = from->get_population(popID).V[i];
Uhh should this be here? and the same for `P[i]` on line 427. Might change behaviour?

2025-05-02 13:53 UTC, markusbattarbee commented on spatial_cells/spatial_cell_cpu.hpp
> +         for (uint i=0; i<6; i++) {
Can you please add these fixes to spatial_cell_gpu.hpp as well?

2025-05-05 08:00 UTC, ykempf commented on sysboundary/outflow.cpp
> +                              // at this stage we don't actually need the VDFs yet I think. And they were crashing LUMI apparently?!
yep

2025-05-05 08:05 UTC, ykempf commented on sysboundary/outflow.cpp
> +
Bit sneaky, but yes, I comment on this so whoever changes next reverts it.

2025-05-05 08:05 UTC, ykempf commented on sysboundary/outflow.cpp
> +
Same story.

2025-05-05 08:10 UTC, ykempf commented on sysboundary/sysboundarycondition.cpp
> +            to->get_population(popID).V[i] = from->get_population(popID).V[i];
I think in my finicky getting-the-very-beginning-diff-free I needed those too. But they get recomputed at the right spot when needed so I think we're good?

2025-05-05 08:10 UTC, ykempf commented on sysboundary/sysboundarycondition.cpp
> +            to->get_population(popID).V[i] = from->get_population(popID).V[i];
`calculateInterpolatedVelocityMoments()` is called right after boundaries in the main loop.

2025-05-05 08:14 UTC, ykempf commented on spatial_cells/spatial_cell_cpu.hpp
> +         for (uint i=0; i<6; i++) {
willco

2025-05-05 08:22 UTC, markusbattarbee commented on sysboundary/sysboundarycondition.cpp
> +            to->get_population(popID).V[i] = from->get_population(popID).V[i];
Ah, right, I remembered that the call to interpolated moments needs to sometimes write values `.P` and sometimes `.P_DT2`, but that's only for the total cellparams. Population-specific values do not keep a separate `_dt2` version. So this is safe indeed.

2025-05-05 08:23 UTC, markusbattarbee approved these changes

2025-05-05 10:15 UTC, ursg approved these changes
Looks good to me, with just a minor style remark

2025-05-05 10:15 UTC, ursg commented on sysboundary/sysboundarycondition.h
> +        }
I still continue to be in favour of actually *not* defining the base class implementations of virtual functions that we don't actually want called anyway. That way, it becomes a compile-time problem.

Does that work in this case, or is the code still too spaghetti to allow for it?

2025-05-05 11:19 UTC, ykempf commented on sysboundary/sysboundarycondition.h
> +        }
We call loops over boundaries, as "always" – if not like this we need an implementation in every other derived class too, which I think we just removed recently?...

2025-05-05 13:38 UTC, merged