Node hours report
fmihpc/vlasiator pull request #1053
Opened 2024-11-05 12:12 UTC by ArnaudLalague

Add core-hours and node-hours to the logfile for every step
Fixed with Yann

2024-11-05 13:01 UTC, ursg approved these changes
Nice addition to the output!

2024-11-05 13:01 UTC, ursg commented on vlasiator.cpp
> +   const double TiB = pow(2,40);
These are never actually used below, as far as I can see?

2024-11-05 13:01 UTC, ursg commented on vlasiator.cpp
> +   MPI_Comm_free(&interComm);
The nodeComm is never freed.

2024-11-05 13:01 UTC, ykempf requested changes

2024-11-05 13:01 UTC, ykempf commented on vlasiator.cpp
> +            logFile << "(TIME) total core-hours " << omp_get_max_threads()*mpiProcs*(currentTime - startTime)/3600 << " h" << endl;
Let's change the wording to "current" or "cumulated" here, "total" at the end (our own copy-paste problem here :)).

2024-11-05 13:01 UTC, ykempf commented on vlasiator.cpp
> +         logFile << "\t (TIME) total core-hours " << omp_get_max_threads()*mpiProcs*(after - startTime)/3600 << " h" << endl;
And I would suggest to reorder and have all of these (above and here) say sth like "(TIME) total x.y node-hours" instead of "node-hours x.y h"

2024-11-05 13:02 UTC, ykempf commented on vlasiator.cpp
> +   MPI_Comm_free(&interComm);
Good catch. Instead in between we were freeing interComm twice. :grimacing:

2024-12-03 08:11 UTC, ykempf commented on vlasiator.cpp
> +   const double TiB = pow(2,40);
Right these came from where we copied the rest of the code and can go indeed.

2025-01-16 13:28 UTC, ykempf approved these changes

2025-01-16 16:23 UTC, markusbattarbee approved these changes

2025-01-17 11:57 UTC, merged