Time-varying BC
fmihpc/vlasiator pull request #570
Opened 2021-09-05 19:21 UTC by henry2004y

Working time-varying boundary. Tested on Vorna, Puhti, and local Ubuntu. 0 test diffs, same performance without the new time-varying option.

Major changes:
1. The source files under `sysboundary` is fully reorganized. `setmaxwellian.cpp` --> `maxwellian.cpp`, `setbyuser.cpp` --> `user.cpp`, and a new file `inflow.cpp` is introduced.
2. The logic behind inflow boundary condition is reimplemented. `Maxwellian` is now a subclass of `Inflow`, as compared to the previous logic where `SetMaxwellian` is a subclass of `SetByUser`. The new User class is an empty class for customized boundary condition for future users.
3. Coding style follows the new Vlasiator format guidelines.

2021-09-06 09:48 UTC, ursg commented
Awesome! I like how you have made the semantics of "sysBoundary" vs. "Boundary" a lot more consistent there.

I'm a bit scared that this might make merging the ionosphere implementation a pain in the neck though (as you have naturally also reformatted and updated some things in ionosphere.cpp). Let me first try to see how much pain it is to rebase my ionosphere branch on top of this.

2021-09-06 10:16 UTC, henry2004y commented
If it turns out to be too hard to resolve the conflicts by hand, here are some major differences before and after the PR:

1. The method `SBC::getSysBoundary` is now renamed to `SBC::getBoundary`.
2. Bool variable `isPeriodic[3] is renamed to `periodic[3]`, since there's also a helper function `isPeriodic()`.
3. New method `updateState()` is added for time-varying BC. For ionosphere it would be empty.
4. Bool variable `isThisDynamic` is renamed to `anyDynamic`.

These may not be complete, but mostly likely are the main changes for `ionosphere.cpp`.

2021-09-11 15:05 UTC, henry2004y commented
I realize that the input file reading function now always searches from the first given timestamp each time it applies. This is not an issue if the number of lines in the input file is small, but certainly can be improved in the next version.

2021-09-24 16:19 UTC, ursg commented
After merging #567, this actually does not cleanly apply to master anymore.

I merged the formatting conflicts and sent you a pull request about it, [here](https://github.com/henry2004y/vlasiator/pull/2).

(Equally, I guess this pull request will require lots of fixing up by others, so I'm a little bit apprehnsive about it).

2021-12-23 09:22 UTC, henry2004y commented
There is potentially another issue related to electron pressure gradient term. Currently the upstream electron pressure term (which I assume refers to the inflow boundary cells) are still fixed from the electron temperature and density given in the configuration file. Maybe this needs to be adjusted as well if we assume charge quasi-neutrality.

2022-01-03 09:39 UTC, markusbattarbee commented
Needs verifying, but I doubt this will in fact be an issue. The upstream value is just a normalization point, and we don't want to change the normalization point throughout the run. So if the actual inflow values change, the local derivatives should still be calculated using the parameter-declared normalization:
https://github.com/fmihpc/vlasiator/blob/4550ac8a0064f88363a8ef0a9d08508a82ebda39/fieldsolver/derivatives.cpp#L64

2022-01-20 09:33 UTC, markusbattarbee requested changes
Hi, I now went through most of the code. It's a bit challenging to see the actual changes because setmaxwellian.cpp was deleted and instead there's the new maxwellian.cpp so I can't actually see the diffs. I'll look into a possibility of re-implementing the file history. 

There were other issues as well with this PR (both technical like already-merged code showing up as new changes) and philosophical.

Although Urs commented positively about renaming some methods (like coding practive 15,  15. The name of the object is implicit, and should be avoided in a method name.) I strongly belive this does NOT take precedence over not disrupting efforts of other people. This is not the only PR dealing with SBCs, we have several! Although they all probably break each other to some degree, each contributor should strive to minimize disruption.

Also, in general, if you want to do whitespace / line return placing / cosmetic PRs, do them separately. Even with turning whitespace diffs off in the github interface, this was a chore to read because of all the changed line breaks - and that does not affect code behaviour.

Also, I see that like you stated, you've changed many functions to return voids. Did you verify carefully that we don't lose any error-catching capability here?

2022-01-20 09:33 UTC, markusbattarbee commented on sysboundary/sysboundary.cpp
> +   for (uint i = 0; i < cells.size(); i++)
Again, I find that for-loops would be better with the curly braces, but it's a matter of preference.
And in matters of preference, I recommend to err on the side of minimazing changes.

2022-01-20 09:33 UTC, markusbattarbee commented on sysboundary/sysboundary.cpp
> +   // flags.  This is needed for the correct use of the boundary local
Oops! Here it actually does mean system boundary local communication patterns. Exactly the difference between system boundaries and process boundaries!

2022-01-20 09:33 UTC, markusbattarbee commented on sysboundary/sysboundary.cpp
> +         if (Parameters::isRestart && !(*it)->doApplyUponRestart())
IMPORTANT! 
Are you sure about this?!?
If called within a restarted run but not requesting reapplyuponrestart, then it is in effect turning dynamic boundary conditions off. 

In my opinion, reapplyuponrestart is only for non-dynamic boundary conditions, as... well, dynamic conditions should be updated regardless of it being a restart or not, so such a flag doesn't make sense for those!

Parameters::isRestart is not turned off after initial handling.

Also, at least in the past, reapplyuponrestart affected the call of applyInitialState().

2022-01-20 09:33 UTC, markusbattarbee commented on sysboundary/sysboundary.cpp
> +      (*it)->updateBoundaryConditionsAfterLoadBalance(mpiGrid, local_cells_on_boundary);
zing

2022-06-30 11:18 UTC, markusbattarbee commented
I had posted this on Flowdock but storing it here so it won't get lost:

> I was able to use these instructions [https://stackoverflow.com/questions/42287533/restore-deleted-file-with-history-in-git](https://stackoverflow.com/questions/42287533/restore-deleted-file-with-history-in-git) to restore history to a deleted / renamed file. Just follow the instructions (including the odd double-copying of files) and it should work! Just be careful about renaming afterwards as that may again do strange things to the history.

2022-06-30 12:02 UTC, henry2004y commented
And a note for myself: `git log --follow` can display the whole history of renamed/moved files.

2022-10-03 13:04 UTC, closed without merging