Updated instructions to fix broken VLSV files
fmihpc/vlasiator pull request #628
Opened 2022-07-20 13:27 UTC by MiroPalmu

2022-07-20 16:25 UTC, ykempf requested changes
Well now that there's also a new feature coming in I'll wait for @ursg's opinion before we merge.

2022-07-20 16:25 UTC, ykempf commented on .gitignore
> +external_libs/
Better add a newline here.

2022-07-20 16:25 UTC, ykempf commented on MAKE/Makefile.cubbli20
> +LIB_SILO = #-L$(LIBRARY_PREFIX)/lib -lsilo
SILO can be removed altogether from here I think.

2022-07-20 16:25 UTC, ykempf commented on MAKE/configure_cubbli20.sh
> +)
Here too add a newline please.

2022-07-27 08:17 UTC, ursg approved these changes
Looks all reasonable. Not sure about that .gitignore addition, but otherwise w could merge this right away.

Watch out that the changes to the carrington makfiles might cause a merge conflict with #629, but that will be pretty easy to resolve, I suppose.

2022-07-27 09:46 UTC, henry2004y commented on MAKE/Makefile.cubbli20
> +# There is script called configure_cubbli20.sh that will install the dependencies automatically.
Miro used shell script for this, which I guess is more universal. I have some extra functionalities in my Python script like checking if any of the dependencies has been installed, etc. The tricky part is the validity of the download links.

It's great to have an automatic script for installation, especially locally.

2022-07-27 13:10 UTC, MiroPalmu commented on MAKE/Makefile.cubbli20
> +# There is script called configure_cubbli20.sh that will install the dependencies automatically.
I tried to keep the script simple and easy to read what it is going to do.

My thought process was to just put commands from [here](https://github.com/fmihpc/vlasiator/wiki/Installing-Vlasiator) to one script that just installs the libraries and nothing else. (Also fix some of the outdated links etc.)

2022-07-27 13:21 UTC, MiroPalmu commented on .gitignore
> +
I removed .gitignore from the PR

2022-08-12 07:27 UTC, merged